RESIZE_DIM: 256
CMR_MULTI:
  CINE_MULTI:
    SAX:
      num_classes: 4
      path: data/CMR-MULTI/CINE_MULTI/SAX_TR/
      path_val: input/CMR-MULTI/CINE_MULTI/SAX_VAL/
      class_weights: [1.0, 19.0, 25.0, 29.0] # example class weights for 4 classes
    2CH:
      num_classes: 3
      path: data/CMR-MULTI/CINE_MULTI/2CH_TR/
      path_val: input/CMR-MULTI/CINE_MULTI/2CH_VAL/
      class_weights: [1.0, 9.0, 11.0] # example class weights for 3 classes
    4CH:
      num_classes: 6
      path: data/CMR-MULTI/CINE_MULTI/4CH_TR/
      path_val: input/CMR-MULTI/CINE_MULTI/4CH_VAL/
      class_weights: [1.0, 11.0, 18.0, 18.0, 23.0, 18.0] # example class weights for 6 classes

  LGE_MULTI:
    SAX:
      num_classes: 5
      path: data/CMR-MULTI/LGE_MULTI/SAX_TR/
      path_val: input/CMR-MULTI/LGE_MULTI/SAX_VAL/
      class_weights: [1.0, 12.0, 17.0, 50.0, 43.0] # example class weights for 5 classes
    2CH:
      num_classes: 4
      path: data/CMR-MULTI/LGE_MULTI/2CH_TR/
      path_val: input/CMR-MULTI/LGE_MULTI/2CH_VAL/
      class_weights: [1.0, 4.0, 11.0, 22.0] # example class weights for 4 classes
    4CH:
      num_classes: 5
      path: data/CMR-MULTI/LGE_MULTI/4CH_TR/
      path_val: input/CMR-MULTI/LGE_MULTI/4CH_VAL/
      class_weights: [1.0, 6.0, 13.0, 10.0, 28.0] # example class weights for 5 classes
    RAS:
      num_classes: 2
      path: data/CMR-MULTI/LGE_MULTI/RAS_TR/
      path_val: input/CMR-MULTI/LGE_MULTI/RAS_VAL/
      class_weights: [1.0, 22.0] # example class weights for 2 classes
