INPUT_DIM_MODEL: 1
LEARNING_RATE: 0.001
FACTOR_LR: 0.5
PATIENCE_LR: 10
PATIENCE_ES: 50
LOG_WANDB: True
BATCH_SIZE: 8
EPOCHS: 200
NUM_WORKERS: 4
PREFETCH_FACTOR: 4
ACCELERATOR: gpu
DEVICES: [0]
SAVE_MODEL_TOP_K: 2
PRECISION: 16-mixed
USE_TRANSFER_LEARNING:
  CINE: False
  LGE: True
PREDICT_FOLDER: "VAL" # VAL or TST
FREEZE_MODEL:
  CINE: False
  LGE: False